[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.0.2", default-features = false, features = ['std'] }
bzip2 = { version = "0.5", default-features = false, features = ["libbz2-rs-sys"] }

